name: Auto Deploy Blog Updates

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '*/30 * * * *' # Cada 30 minutos busca actualizaciones
  workflow_dispatch: # Permite ejecutar manualmente desde GitHub

jobs:
  check-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build project
      run: npm run build
      
    - name: Deploy to Hostinger
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASS }}
        port: 21
        local-dir: ./out/
        server-dir: ./public_html/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/.env*
          **/README.md
        
    - name: Deployment Success Notification
      if: success()
      run: echo "🚀 Deployment successful! Site updated at $(date)"
      
    - name: Deployment Failed Notification  
      if: failure()
      run: echo "❌ Deployment failed! Check logs for details"